FROM nvidia/cuda:12.6.3-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

RUN pip install paddlepaddle-gpu==3.2.1 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
RUN pip install paddleocr[doc-parser]
RUN pip install uvicorn fastapi python-multipart requests

WORKDIR /home/paddleocr
COPY server_classic.py server.py

ENV PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK=True
EXPOSE 8080

CMD ["python3", "server.py"]
